# version: '3'

name: docker-knowledge-lab
services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    # deploy:
    #   mode: replicated
    #   replicas: 3
  echo-server:
    image: hashicorp/http-echo
    ports:
      - "5678:5678"
    command: [ "-text", "hello world" ]
